### ISSUE TITLE
false positive windows defender

### ISSUE THREAD

**Issue by costasto** [alex-free/libcrypt-patcher#2]
this tool is amazing it does what it says. but the latest version gives false possitive to windows defender. can you do something for it?

**Comment by alex-free** [comment]
Looks like the file can be submitted to Microsoft to _possibly_ remove the false flag (although I'd need a Microsoft account to do so).  Another thing might just be that the release is too new and not yet marked as safe on their end (which is a horrible system in itself). Windows Defender is really annoying, it can be disabled temporarily in Windows Settings so that you can use the latest release. Going to close this since this is an issue with Windows and not the software in itself, but thanks for the report.
